dataset:
  dir: "data/ptb_3/dataset/depth"
layer_idx: 7
experiment: "depth"
model_name: "bert-base-cased"
probe:
  finetune-model: "linear"
  epochs: 8
  batch_size: 20
  rep_dim: 64
  input_size: 768
  output_dir: "outputs/ptb_3/depth"
  lr: "1e-2"