dataset:
  dir: "data/en_ewt-ud/dataset/dep"
  task_name: "dep"
layer_idx: 3
model_name: "google/multiberts-seed_0-step_200k"
probe:
  finetune-model: "linear"
  epochs: 1
  batch_size: 32
  num_labels: 53
  input_size: 768
  output_dir: "outputs/en_ewt-ud/dep"
  lr: "0.001"
