dataset:
  batch_size: 20
  corpus:
    dev_path: en_ewt-ud-dev.conllu
    root: ./data/structural-probes/conllu/
    test_path: en_ewt-ud-test.conllu
    train_path: en_ewt-ud-train.conllu
  embeddings:
    dev_path: dev.hdf5
    root: ./data/structural-probes/embeddings/base
    test_path: test.hdf5
    train_path: train.hdf5
    type: subword
  observation_fieldnames:
  - index
  - sentence
  - lemma_sentence
  - upos_sentence
  - xpos_sentence
  - morph
  - head_indices
  - governance_relations
  - secondary_relations
  - extra_info
  - embeddings
model:
  hidden_dim: 768
  model_layer: 7
  model_type: BERT-disk
  use_disk: true
probe:
  diagonal: false
  maximum_rank: 128
  params_path: predictor.params
  psd_parameters: true
  task_name: parse-distance
  task_signature: word_pair
probe_training:
  epochs: 16
  loss: L1
reporting:
  observation_paths:
    dev_path: dev.observations
    test_path: test.observations
    train_path: train.observations
  prediction_paths:
    dev_path: dev.predictions
    test_path: test.predictions
    train_path: train.predictions
  reporting_methods:
  - spearmanr
  - uuas
  root: ./outputs/structural/results/base
