dataset:
  dir: "data/en_ewt-ud/dataset/fpos"
  task_name: "fpos"
layer_idx: 2
model_name: "google/multiberts-seed_0-step_1000k"
probe:
  finetune-model: "linear"
  epochs: 1
  batch_size: 32
  num_labels: 38
  input_size: 768
  output_dir: "outputs/en_ewt-ud/fpos"
  lr: "0.001"
