dataset:
  dir: "data/ptb_3/dataset/depth"
layer_idx: 1
experiment: "depth"
model_name: "google/multiberts-seed_0-step_0k"
probe:
  finetune-model: "linear"
  epochs: 10
  batch_size: 20
  rep_dim: 64
  input_size: 768
  output_dir: "outputs/ptb_3/depth"
  lr: "1e-2"
