dataset:
  dir: "data/ontonotes/dataset/phrase_start"
  task_name: "phrase_start"
layer_idx: 7
model_name: "bert-base-cased"
probe:
  finetune-model: "linear"
  epochs: 1
  batch_size: 32
  num_labels: 2
  input_size: 768
  output_dir: "outputs/ontonotes/phrase_start"
  lr: "0.001"